import { Product } from "@/entities/product/types";
import { Review } from "@/entities/review/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    category_id: "1",
    name: {
      ko: "글로우 세럼 에센스",
      en: "Glow Serum Essence",
      "zh-CN": "光彩精华液",
      "zh-TW": "光彩精華液",
    },
    description: {
      ko: "히알루론산과 나이아신아마이드가 함유된 고보습 세럼",
      en: "High-moisture serum with hyaluronic acid and niacinamide",
      "zh-CN": "含透明质酸和烟酰胺的高保湿精华",
      "zh-TW": "含透明質酸和菸鹼醯胺的高保濕精華",
    },
    price: 48000,
    sale_price: 35000,
    images: ["/images/products/serum-1.jpg"],
    rating: 4.8,
    review_count: 2847,
    is_best: true,
    is_new: false,
    created_at: "2026-01-01",
  },
  {
    id: "2",
    category_id: "1",
    name: {
      ko: "퓨어 모이스처 크림",
      en: "Pure Moisture Cream",
      "zh-CN": "纯净保湿霜",
      "zh-TW": "純淨保濕霜",
    },
    description: {
      ko: "시어버터와 세라마이드로 깊은 보습을 선사하는 데일리 크림",
      en: "Daily cream with deep moisture from shea butter and ceramide",
      "zh-CN": "含乳木果油和神经酰胺的深层保湿日霜",
      "zh-TW": "含乳木果油和神經醯胺的深層保濕日霜",
    },
    price: 52000,
    sale_price: null,
    images: ["/images/products/cream-1.jpg"],
    rating: 4.7,
    review_count: 1923,
    is_best: true,
    is_new: false,
    created_at: "2026-01-05",
  },
  {
    id: "3",
    category_id: "2",
    name: {
      ko: "벨벳 립 틴트",
      en: "Velvet Lip Tint",
      "zh-CN": "丝绒唇釉",
      "zh-TW": "絲絨唇釉",
    },
    description: {
      ko: "부드러운 벨벳 텍스처의 고발색 립 틴트",
      en: "High-pigment lip tint with soft velvet texture",
      "zh-CN": "柔软丝绒质地的高显色唇釉",
      "zh-TW": "柔軟絲絨質地的高顯色唇釉",
    },
    price: 22000,
    sale_price: 17600,
    images: ["/images/products/lip-1.jpg"],
    rating: 4.9,
    review_count: 3521,
    is_best: true,
    is_new: false,
    created_at: "2026-01-10",
  },
  {
    id: "4",
    category_id: "1",
    name: {
      ko: "비타민C 브라이트닝 앰플",
      en: "Vitamin C Brightening Ampoule",
      "zh-CN": "维C亮白安瓶",
      "zh-TW": "維C亮白安瓶",
    },
    description: {
      ko: "순수 비타민C 15% 함유 브라이트닝 앰플",
      en: "Brightening ampoule with 15% pure vitamin C",
      "zh-CN": "含15%纯维C的亮白安瓶",
      "zh-TW": "含15%純維C的亮白安瓶",
    },
    price: 38000,
    sale_price: 28500,
    images: ["/images/products/ampoule-1.jpg"],
    rating: 4.6,
    review_count: 1456,
    is_best: true,
    is_new: false,
    created_at: "2026-01-15",
  },
  {
    id: "5",
    category_id: "6",
    name: {
      ko: "데일리 선 에센스 SPF50+",
      en: "Daily Sun Essence SPF50+",
      "zh-CN": "日常防晒精华 SPF50+",
      "zh-TW": "日常防曬精華 SPF50+",
    },
    description: {
      ko: "가벼운 텍스처의 자외선 차단 에센스",
      en: "Lightweight UV protection essence",
      "zh-CN": "轻盈质地的防紫外线精华",
      "zh-TW": "輕盈質地的防紫外線精華",
    },
    price: 28000,
    sale_price: null,
    images: ["/images/products/sun-1.jpg"],
    rating: 4.7,
    review_count: 2134,
    is_best: false,
    is_new: true,
    created_at: "2026-02-01",
  },
  {
    id: "6",
    category_id: "3",
    name: {
      ko: "로즈 바디 로션",
      en: "Rose Body Lotion",
      "zh-CN": "玫瑰身体乳",
      "zh-TW": "玫瑰身體乳",
    },
    description: {
      ko: "다마스크 로즈 오일이 함유된 보습 바디 로션",
      en: "Moisturizing body lotion with damask rose oil",
      "zh-CN": "含大马士革玫瑰油的保湿身体乳",
      "zh-TW": "含大馬士革玫瑰油的保濕身體乳",
    },
    price: 32000,
    sale_price: 25600,
    images: ["/images/products/body-1.jpg"],
    rating: 4.5,
    review_count: 987,
    is_best: false,
    is_new: true,
    created_at: "2026-02-05",
  },
  {
    id: "7",
    category_id: "7",
    name: {
      ko: "시카 진정 마스크팩",
      en: "Cica Soothing Mask Pack",
      "zh-CN": "积雪草舒缓面膜",
      "zh-TW": "積雪草舒緩面膜",
    },
    description: {
      ko: "민감한 피부를 위한 시카 진정 시트 마스크",
      en: "Cica soothing sheet mask for sensitive skin",
      "zh-CN": "敏感肌肤专用积雪草舒缓面膜",
      "zh-TW": "敏感肌膚專用積雪草舒緩面膜",
    },
    price: 3000,
    sale_price: null,
    images: ["/images/products/mask-1.jpg"],
    rating: 4.8,
    review_count: 4521,
    is_best: false,
    is_new: true,
    created_at: "2026-02-10",
  },
  {
    id: "8",
    category_id: "4",
    name: {
      ko: "실크 헤어 오일 세럼",
      en: "Silk Hair Oil Serum",
      "zh-CN": "丝滑护发精油",
      "zh-TW": "絲滑護髮精油",
    },
    description: {
      ko: "아르간 오일과 카멜리아 오일로 만든 헤어 세럼",
      en: "Hair serum made with argan oil and camellia oil",
      "zh-CN": "摩洛哥坚果油和山茶花油制成的护发精华",
      "zh-TW": "摩洛哥堅果油和山茶花油製成的護髮精華",
    },
    price: 26000,
    sale_price: 20800,
    images: ["/images/products/hair-1.jpg"],
    rating: 4.6,
    review_count: 876,
    is_best: false,
    is_new: true,
    created_at: "2026-02-15",
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    product_id: "1",
    user_name: "김*영",
    rating: 5,
    content:
      "피부가 정말 촉촉해졌어요! 세럼 텍스처가 가볍고 흡수도 빨라서 매일 쓰고 있어요. 강추합니다!",
    avatar_url: null,
    created_at: "2026-02-10",
  },
  {
    id: "2",
    product_id: "3",
    user_name: "이*희",
    rating: 5,
    content:
      "립 틴트 발색이 예술이에요! 하루 종일 지속되고 건조하지 않아요. 3개 색상 다 구매했어요~",
    avatar_url: null,
    created_at: "2026-02-08",
  },
  {
    id: "3",
    product_id: "2",
    user_name: "Sarah K.",
    rating: 4,
    content:
      "Love this cream! My skin feels so soft and hydrated. The texture is perfect for layering under makeup.",
    avatar_url: null,
    created_at: "2026-02-05",
  },
  {
    id: "4",
    product_id: "4",
    user_name: "박*수",
    rating: 5,
    content:
      "비타민C 앰플 쓰고 나서 피부톤이 확실히 밝아졌어요. 자극 없이 순하게 쓸 수 있어서 좋아요.",
    avatar_url: null,
    created_at: "2026-02-03",
  },
  {
    id: "5",
    product_id: "1",
    user_name: "田中美咲",
    rating: 5,
    content:
      "韓国コスメ最高です！このセラムを使ってから肌がもちもちになりました。リピ確定です！",
    avatar_url: null,
    created_at: "2026-02-01",
  },
  {
    id: "6",
    product_id: "7",
    user_name: "최*진",
    rating: 5,
    content:
      "민감 피부인데 시카 마스크팩 쓰면 바로 진정돼요. 트러블 날 때 필수템이에요!",
    avatar_url: null,
    created_at: "2026-01-28",
  },
];

export const mockBanners = [
  {
    id: "1",
    image_url: "/images/banners/banner-1.jpg",
    link: "/products",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "2",
    image_url: "/images/banners/banner-2.jpg",
    link: "/products",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "3",
    image_url: "/images/banners/banner-3.jpg",
    link: "/about",
    sort_order: 3,
    is_active: true,
  },
];

export const mockCategories = [
  { id: "1", slug: "skincare", icon: "Droplets", sort_order: 1 },
  { id: "2", slug: "makeup", icon: "Palette", sort_order: 2 },
  { id: "3", slug: "bodycare", icon: "Bath", sort_order: 3 },
  { id: "4", slug: "haircare", icon: "Scissors", sort_order: 4 },
  { id: "5", slug: "fragrance", icon: "Flower2", sort_order: 5 },
  { id: "6", slug: "suncare", icon: "Sun", sort_order: 6 },
  { id: "7", slug: "masks", icon: "Smile", sort_order: 7 },
  { id: "8", slug: "sets", icon: "Gift", sort_order: 8 },
];
